[package]
name = "rvc"
version = "0.1.0-alpha"
edition = "2021"
authors = ["DarkJoij"]
license = "Apache-2.0"
repository = "https://github.com/DarkJoij/rvc"
description = "A Git-compatible Version Control System based on The Rust Programming Language."

# [dependencies]
